export const FORMATIONS = [ '1211', '2111', '1121' ]

export const STRIKER_POSITION = "ST";
export const MIDFIELDER_POSITION = "CM";
export const DEFENDER_POSITION = "CB";
export const GOALKEEPER_POSITION = "GK";

export const PLAYERS = [
    //strikers
    { name: 'Pelé', position: 'ST' },
    { name: 'Diego Maradona', position: 'ST' },
    { name: 'Lionel Messi', position: 'ST' },
    { name: 'Cristiano Ronaldo', position: 'ST' },
    { name: 'Johan Cruyff', position: 'ST' },
    { name: 'Ronaldo Nazário', position: 'ST' },
    { name: 'Thierry Henry', position: 'ST' },
    { name: 'Alfredo Di Stéfano', position: 'ST' },
    { name: 'George Best', position: 'ST' },
    { name: 'Eusébio', position: 'ST' },
    { name: 'Marco van Basten', position: 'ST' },
    { name: 'Ferenc Puskás', position: 'ST' },
    { name: 'Gerd Müller', position: 'ST' },
    { name: 'Raul Gonzalez', position: 'ST' },
    { name: 'Roberto Baggio', position: 'ST' },
    { name: 'Paolo Rossi', position: 'ST' },
    { name: 'David Villa', position: 'ST' },
    { name: 'Alessandro Del Piero', position: 'ST' },
    { name: 'Zlatan Ibrahimović', position: 'ST' },
    { name: 'Fernando Peyroteo', position: 'ST' },
    //midfielders
    { name: 'Andres Iniesta', position: 'CM' },
    { name: 'Xavi Hernandez', position: 'CM' },
    { name: 'Zinedine Zidane', position: 'CM' },
    { name: 'Michel Platini', position: 'CM' },
    { name: 'Frank Lampard', position: 'CM' },
    { name: 'Andrea Pirlo', position: 'CM' },
    { name: 'Paul Scholes', position: 'CM' },
    { name: 'Steven Gerrard', position: 'CM' },
    { name: 'Luka Modric', position: 'CM' },
    { name: 'Kevin De Bruyne', position: 'CM' },
    { name: 'Kaka', position: 'CM' },
    { name: 'Lothar Matthaus', position: 'CM' },
    { name: 'Zico', position: 'CM' },
    { name: 'Cesc Fabregas', position: 'CM' },
    { name: 'Gheorghe Hagi', position: 'CM' },
    { name: 'Socrates', position: 'CM' },
    { name: 'Raymond Kopa', position: 'CM' },
    { name: 'George Best', position: 'CM' },
    { name: 'Michael Ballack', position: 'CM' },
    { name: 'Gianfranco Zola', position: 'CM' },
    { name: 'Guti', position: 'CM' },
    { name: 'Deco', position: 'CM' },
    { name: 'Fernando Redondo', position: 'CM' },
    { name: 'Johan Neeskens', position: 'CM' },
    { name: 'Claude Makélélé', position: 'CM' },
    { name: 'Patrick Vieira', position: 'CM' },
    { name: 'Luis Suárez Miramontes', position: 'CM' },
    { name: 'Ruud Gullit', position: 'CM' },
    { name: 'Fernando Hierro', position: 'CM' },
    { name: 'Gianni Rivera', position: 'CM' },
    { name: 'Javier Zanetti', position: 'CM' },
    { name: 'Gerson', position: 'CM' },
    { name: 'Sócrates', position: 'CM' },
    { name: 'Didier Deschamps', position: 'CM' },
    { name: 'Bobby Charlton', position: 'CM' },
    { name: 'Gordon Banks', position: 'CM' },
    { name: 'Roger Milla', position: 'CM' },
    { name: 'Dino Zoff', position: 'CM' },
    { name: 'Giuseppe Meazza', position: 'CM' },
    { name: 'Gigi Riva', position: 'CM' },
    //   center backs
    { name: 'Franz Beckenbauer', position: 'CB' },
    { name: 'Bobby Moore', position: 'CB' },
    { name: 'Paolo Maldini', position: 'CB' },
    { name: 'Franco Baresi', position: 'CB' },
    { name: 'Fernando Hierro', position: 'CB' },
    { name: 'John Terry', position: 'CB' },
    { name: 'Alessandro Nesta', position: 'CB' },
    { name: 'Carles Puyol', position: 'CB' },
    { name: 'Fabio Cannavaro', position: 'CB' },
    { name: 'Giorgio Chiellini', position: 'CB' },
    { name: 'Maldini', position: 'CB' },
    { name: 'Rio Ferdinand', position: 'CB' },
    { name: 'Lucio', position: 'CB' },
    { name: 'Ronald Koeman', position: 'CB' },
    { name: 'Sol Campbell', position: 'CB' },
    { name: 'Franco Baresi', position: 'CB' },
    { name: 'Daniel Passarella', position: 'CB' },
    { name: 'Giacinto Facchetti', position: 'CB' },
    { name: 'Fernando Hierro', position: 'CB' },
    { name: 'Ruud Krol', position: 'CB' },
    { name: 'Thiago Silva', position: 'CB' },
    { name: 'Alessandro Costacurta', position: 'CB' },
    { name: 'Laurent Blanc', position: 'CB' },
    { name: 'Jaap Stam', position: 'CB' },
    { name: 'Gary Pallister', position: 'CB' },
    { name: 'Ricardo Carvalho', position: 'CB' },
    { name: 'Jaime Ayovi', position: 'CB' },
    { name: 'Andrea Barzagli', position: 'CB' },
    { name: 'Lucas Biglia', position: 'CB' },
    { name: 'Vincent Kompany', position: 'CB' },
    { name: 'Thiago Silva', position: 'CB' },
    { name: 'Alessandro Costacurta', position: 'CB' },
    { name: 'Laurent Blanc', position: 'CB' },
    { name: 'Jaap Stam', position: 'CB' },
    { name: 'Gary Pallister', position: 'CB' },
    { name: 'Ricardo Carvalho', position: 'CB' },
    { name: 'Jaime Ayovi', position: 'CB' },
    { name: 'Andrea Barzagli', position: 'CB' },
    { name: 'Lucas Biglia', position: 'CB' },
    { name: 'Vincent Kompany', position: 'CB' },
    //goalkeepers
    { name: 'Lev Yashin', position: 'GK' },
    { name: 'Gianluigi Buffon', position: 'GK' },
    { name: 'Iker Casillas', position: 'GK' },
    { name: 'Dino Zoff', position: 'GK' },
    { name: 'Peter Schmeichel', position: 'GK' },
    { name: 'Oliver Kahn', position: 'GK' },
    { name: 'Edwin van der Sar', position: 'GK' },
    { name: 'Manuel Neuer', position: 'GK' },
    { name: 'Gordon Banks', position: 'GK' },
    { name: 'Petr Čech', position: 'GK' },   
];